extends Node

#func _ready():
	#print("Enum ready at: ", Time.get_ticks_msec())


enum Style {F_BODY,M_BODY,F_HAIR,M_HAIR,F_SHIRT,M_SHIRT,F_PANTS,M_PANTS,F_SHOES,M_SHOES}
enum Tool {SWING,AXE,HOE,SHOVEL,PICK,HAMMER,SEED,WATER,FISH}
enum Machine {SPRINKLER, FISHER, SCARECROW, DELETE}
enum Seed {STRAWBERRY,CARROT,BLUEBERRY,TOMATO,TURNIP}
enum Item {STRAWBERRY,CARROT,BLUEBERRY,TOMATO,TURNIP,WOOD,APPLE,CORN,WHEAT,PUMPKIN,FISH}
enum State {DEFAULT, SWORD, FISHING, BUILDING, SHOP, HOEING, SEEDING}
enum SlotType {INVENTORY,STORAGE}
enum InvActionStates {DEFAULT,MOVE,SWAP,COMBINE,SPLIT}
enum MenuStates {DEFAULT,MAIN_INVENTORY}

enum UIState {
	NONE,
	INVENTORY,
	VENDOR,
	PAUSED
	#CRAFTING,
	#DIALOGUE,
}




# Bottom
